#ifndef IIR_RESAMPLE_TABLE_H
#define IIR_RESAMPLE_TABLE_H

// Donot edit, this file is generated by gen_resample_iir_tables.m

#include "speech_eq.h"

static EqConfigRaw iir_resample_table_1to2 = {
	.gain = 0.f,
	.num = 3,
	.param = {
		{-6.140921105e-16f,  1.733238012e-02f,  2.958822364e-02f,  5.917705528e-02f,  2.958827863e-02f},
		{ 5.412337245e-16f,  1.715728753e-01f,  1.000000000e+00f,  2.004312897e+00f,  1.004331631e+00f},
		{-8.881784197e-16f,  5.887907065e-01f,  1.000000000e+00f,  1.995666555e+00f,  9.956852002e-01f},
	},
};

static EqConfigRaw iir_resample_table_1to3 = {
	.gain = 0.f,
	.num = 3,
	.param = {
		{-5.445091873e-01f,  8.901837459e-02f,  4.310497637e-03f,  8.649682491e-03f,  4.339248582e-03f},
		{-6.202041029e-01f,  2.404082058e-01f,  1.000000000e+00f,  1.999981853e+00f,  9.999965763e-01f},
		{-8.168974465e-01f,  6.337948931e-01f,  1.000000000e+00f,  1.993362949e+00f,  9.933776122e-01f},
	},
};

static EqConfigRaw iir_resample_table_1to6 = {
	.gain = 0.f,
	.num = 3,
	.param = {
		{-1.167966368e+00f,  3.486513940e-01f,  1.325928963e-04f,  2.659695724e-04f,  1.333782245e-04f},
		{-1.279632425e+00f,  4.775922501e-01f,  1.000000000e+00f,  1.999969278e+00f,  9.999808654e-01f},
		{-1.533589697e+00f,  7.708368489e-01f,  1.000000000e+00f,  1.994119546e+00f,  9.941310429e-01f},
	},
};

#endif
