CHIP		?= best2000

DEBUG		?= 1

FPGA		?= 0

MBED		?= 1

RTOS		?= 1

WATCHER_DOG ?= 0

MCU_HIGH_PERFORMANCE_MODE ?= 0
DEBUG_PORT	?= 1
# 0: usb
# 1: uart0
# 2: uart1

FLASH_CHIP	?= GD25Q80C GD25Q32C GD25LQ32C EN25S80B
# GD25Q80C
# GD25Q32C
#GD25LQ32C
#EN25S80B
# ALL

AUDIO_OUTPUT_MONO ?= 0

AUDIO_OUTPUT_DIFF ?= 0

HW_FIR_EQ_PROCESS ?= 0

SW_IIR_EQ_PROCESS ?= 0

HW_CODEC_IIR_EQ_PROCESS ?= 1

AUDIO_RESAMPLE ?= 1

TWS_SBC_PATCH_SAMPLES ?= 0

AUDIO_OUTPUT_VOLUME_DEFAULT ?= 17
# range:1~17

AUDIO_INPUT_CAPLESSMODE ?= 0

AUDIO_INPUT_LARGEGAIN ?= 0

#AUDIO_RESAMPLE ?= 0

AUDIO_CODEC_ASYNC_CLOSE ?= 0

AUDIO_SCO_BTPCM_CHANNEL ?= 1

AUDIO_EQ_PROCESS ?= 0

SPEECH_TX_AEC ?= 0

SPEECH_TX_NS ?= 0

SPEECH_TX_NS2 ?= 1

SPEECH_TX_2MIC_NS2 ?= 1

WEBRTC_AEC_FIX ?= 1

SPEECH_TX_AGC ?= 0

SPEECH_TX_2MIC_NS ?= 0

SPEECH_TX_2MIC_NS3 ?= 0

SPEECH_STREAM_UNIT_128 ?= 1

export SPEECH_STREAM_UNIT_128_8K ?= 1

export SPEECH_STREAM_UNIT_120_8K ?= 0

SPEECH_RX_PLC ?= 1

SPEECH_TX_EQ ?= 0

SPEECH_RX_NS ?= 0

SPEECH_RX_EQ ?= 0

LARGE_RAM ?= 1

HFP_1_6_ENABLE ?= 1

MSBC_PLC_ENABLE ?= 1

MSBC_PLC_ENCODER ?= 1

MSBC_16K_SAMPLE_RATE ?= 1

SBC_FUNC_IN_ROM ?= 1

VOICE_DETECT ?= 0

VOICE_PROMPT ?= 1

VOICE_RECOGNITION ?= 0

BLE ?= 0

BTADDR_GEN ?= 1

BT_ONE_BRING_TWO ?= 0

A2DP_AAC_ON ?= 1

A2DP_AAC_DIRECT_TRANSFER ?= 1

FACTORY_MODE ?= 1

ENGINEER_MODE ?= 1

ULTRA_LOW_POWER	?= 1

DAC_CLASSG_ENABLE ?= 1

NO_SLEEP ?= 0

export POWER_MODE	?= DIG_DCDC

ifeq ($(CURRENT_TEST),1)
export VCODEC_VOLT ?= 1.5V

export VCORE_LDO_OFF ?= 1
else
export VCODEC_VOLT ?= 1.6V
endif

export VCRYSTAL_OFF ?= 1

export TWS   ?= 1

export JTAG_BT ?= 1
export BT_MIC_GAIN_CTRL   ?= 1

OSC_26M_X4_AUD2BB ?= 1

export SW_PLAYBACK_RESAMPLE ?= 0
export RESAMPLE_ANY_SAMPLE_RATE ?= 0

ifneq ($(SW_PLAYBACK_RESAMPLE),1)
export APP_MUSIC_26M ?= 1
endif

init-y		:=
core-y		:= platform/ services/ apps/ utils/cqueue/ utils/list/ services/multimedia/ utils/intersyshci/
KBUILD_CPPFLAGS += -Iplatform/cmsis/inc -Iservices/audioflinger -Iplatform/drivers/codec -Iplatform/hal -Iservices/fs/ -Iservices/fs/sd -Iservices/fs/fat  -Iservices/fs/fat/ChaN -Iplatform/drivers/norflash

KBUILD_CPPFLAGS += \
    -D_AUTO_SWITCH_POWER_MODE__ \
    -D_BEST1000_QUAL_DCDC_ \
    -D__APP_KEY_FN_STYLE_A__ \
    -D__TWS__  \
    -D__TWS_RECONNECT_USE_BLE__  \
    -D__TWS_OUTPUT_CHANNEL_SELECT__  \
    -D__EARPHONE_STAY_BOTH_SCAN__  \
    -D__EARPHONE_STAY_BCR_SLAVE__ \
    -DSLAVE_USE_ENC_SINGLE_SBC    \
    -D__TWS_CALL_DUAL_CHANNEL__  \
    -DBT_XTAL_SYNC   \
    -D__TWS_1CHANNEL_PCM__  \
 


#    -D__3M_PACK__
#-D_AUTO_SWITCH_POWER_MODE__
#-D_BEST1000_QUAL_DCDC_
#-D__APP_KEY_FN_STYLE_A__
#-D__APP_KEY_FN_STYLE_B__
#-D__BT_ONE_BRING_TWO__
#-D__EARPHONE_STAY_BOTH_SCAN__
#-D__POWERKEY_CTRL_ONOFF_ONLY__
#-DFLASH_REGION_BASE=0x6C018000
#-D__TWS_1CHANNEL_PCM__
#-D__TWS_RESAMPLE_ADJUST__


LDS_FILE	:= best1000.lds

KBUILD_CPPFLAGS +=

KBUILD_CFLAGS +=

LIB_LDFLAGS += -lstdc++ -lsupc++

#CFLAGS_IMAGE += -u _printf_float -u _scanf_float

#LDFLAGS_IMAGE += --wrap main

